baseURL = "https://brandongiesing.com/"
languageCode = "en-US"
title = "BrandonGiesing.com"
theme = ["cosicast","after-dark"]

[params.hackcss]
  disabled = false
  mode = "hack"
  palette = "cosicast"

disqusShortname = "brandongiesing"
footnoteReturnLinkContents = "↩" # Provides a nicer footnote return link
enableRobotsTXT = true # Suggested, enable robots.txt file

[[menu.main]]
  name = "Home"
  weight = 1
  identifier = "home"
  url = "/"
[[menu.main]]
  name = "Blog"
  weight = 2
  identifier = "blog"
  url = "/post"
[[menu.main]]
  name = "CosiCast"
  weight = 3
  identifier = "cosicast"
  url = "/cosicast"
[[menu.main]]
  name = "Money Routine"
  weight = 4
  identifier = "money"
  url = "/money/"
[[menu.main]]
  name = "Projects"
  weight = 5
  identifier = "projects"
  url = "/projects"
[[menu.main]]
  name = "Support Me"
  weight = 5
  identifier = "supportme"
  url = "/supportme"
[[menu.main]]
  name = "Search"
  weight = 6
  identifier = "search"
  url = "/search"

[permalinks]
  post = "/:year/:month/:day/:title/"

[params]
  author = "Brandon Giesing"
  hide_author = true
  show_menu = true
  powered_by = false

[params.seo]
  telegram_channel = "CosiCorner"

[outputs]
  home = ["HTML", "RSS", "JSON"]
  section = ["HTML", "RSS", "JSON"]

[privacy]
  [privacy.instagram]
    simple = true
  [privacy.twitter]
    enableDNT = true
  [privacy.youtube]
    privacyEnhanced = true
