baseURL = "https://brandongiesing.com/"
languageCode = "en-US"
title = "BrandonGiesing.com"
theme = "afterdark"
theme_variant = "hack solarized-dark"

disqusShortname = "brandongiesing"
footnoteReturnLinkContents = "↩" # Provides a nicer footnote return link
enableRobotsTXT = true # Suggested, enable robots.txt file

[[menu.main]]
  name = "Home"
  weight = 1
  identifier = "home"
  url = "/"
[[menu.main]]
  name = "Blog"
  weight = 2
  identifier = "blog"
  url = "https://steemit.com/@brandongiesing/"
[[menu.main]]
  name = "CosiCast"
  weight = 3
  identifier = "cosicast"
  url = "/cosicast"
[[menu.main]]
  name = "Money Routine"
  weight = 4
  identifier = "money"
  url = "/money/"
[[menu.main]]
  name = "Other Projects"
  weight = 5
  identifier = "projects"
  url = "/projects"
[[menu.main]]
  name = "Support Me"
  weight = 5
  identifier = "supportme"
  url = "/supportme"
[[menu.main]]
  name = "Search"
  weight = 6
  identifier = "search"
  url = "/search"

[permalinks]
  post = "/:year/:month/:day/:title/"

[params]
  author = "Brandon Giesing" # Optional, controls author name display on posts
  hide_author = true # Optional, set true to hide author name on posts
  show_menu = true # Optional, set true to enable section menu
  powered_by = false # Optional, set false to disable credits

[outputs]
  home = ["HTML", "RSS", "JSON"]
  section = ["HTML", "RSS", "JSON"]
  
[privacy]
  [privacy.googleAnalytics]
    disable = true
  [privacy.instagram]
    simple = true
  [privacy.twitter]
    enableDNT = true
  [privacy.youtube]
    privacyEnhanced = true
