baseURL = "https://brandongiesing.com/"
languageCode = "en-us"
title = "BrandonGiesing.com"
theme = "afterdark"

[[menu.main]]
  name = "Home"
  weight = 1
  identifier = "home"
  url = "/"
[[menu.main]]
  name = "Blog"
  weight = 2
  identifier = "blog"
  url = "https://steemit.com/@brandongiesing/"
[[menu.main]]
  name = "CosiCast"
  weight = 3
  identifier = "cosicast"
  url = "/cosicast"
[[menu.main]]
  name = "Money Routine"
  weight = 4
  identifier = "money"
  url = "/money/"
[[menu.main]]
  name = "Other Projects"
  weight = 5
  identifier = "projects"
  url = "/projects"
[[menu.main]]
  name = "Support Me"
  weight = 5
  identifier = "supportme"
  url = "/supportme"

