[build]
  publish = "public"
  command = "hugo"
# build a preview of the site [hugo --buildFuture]
[context.deploy-preview]
  command = "hugo --buildFuture"
# The default version you use for production if you don't use context
[build.environment]
  HUGO_VERSION = "0.44"
# The version you use for production
[context.production.environment]
  HUGO_VERSION = "0.44"
[context.deploy-preview.environment]
  HUGO_VERSION = "0.44"
